#!/usr/bin/env bash
#
# VPS Panel one-line installer.
#
# Usage on a fresh Linux VPS (Ubuntu/Debian/RHEL/CentOS):
#
#   curl -fsSL https://raw.githubusercontent.com/YOUR_USER/vps-panel/main/install.sh | bash
#
# Or with options:
#
#   curl -fsSL .../install.sh | INSTALL_DIR=/opt/vps-panel REPO_URL=https://github.com/YOUR_USER/vps-panel.git bash
#
# Re-running is idempotent — secrets and the database are preserved.

set -euo pipefail

# ---- config (override via env) ----------------------------------------------
: "${INSTALL_DIR:=/opt/vps-panel}"
: "${REPO_URL:=https://github.com/YOUR_USER/vps-panel.git}"
: "${REPO_BRANCH:=main}"

# Colors for output (skip if non-tty)
if [ -t 1 ]; then
  C_GREEN='\033[0;32m'; C_RED='\033[0;31m'; C_YELLOW='\033[0;33m'
  C_BLUE='\033[0;34m'; C_BOLD='\033[1m'; C_RESET='\033[0m'
else
  C_GREEN=''; C_RED=''; C_YELLOW=''; C_BLUE=''; C_BOLD=''; C_RESET=''
fi

step()  { echo -e "${C_BLUE}${C_BOLD}▸ $*${C_RESET}"; }
ok()    { echo -e "${C_GREEN}  ✓ $*${C_RESET}"; }
warn()  { echo -e "${C_YELLOW}  ⚠ $*${C_RESET}"; }
fail()  { echo -e "${C_RED}  ✗ $*${C_RESET}"; exit 1; }

# ---- preflight --------------------------------------------------------------
if [ "$(id -u)" -ne 0 ]; then
  fail "Run as root (e.g. with sudo) — installer needs to install packages + manage Docker."
fi

if ! command -v uname >/dev/null 2>&1 || [ "$(uname -s)" != "Linux" ]; then
  fail "This installer is Linux-only. Run on your VPS, not your laptop."
fi

step "Detecting OS"
if [ -r /etc/os-release ]; then
  # shellcheck source=/dev/null
  . /etc/os-release
  OS_ID="${ID:-unknown}"
  ok "$NAME ${VERSION_ID:-}"
else
  fail "Cannot detect OS — /etc/os-release missing."
fi

# ---- install Docker if missing ---------------------------------------------
step "Checking Docker"
if ! command -v docker >/dev/null 2>&1; then
  warn "Docker not installed — installing from get.docker.com (this takes ~1 minute)"
  curl -fsSL https://get.docker.com | sh
  ok "Docker installed: $(docker --version)"
else
  ok "Docker present: $(docker --version)"
fi

if ! docker compose version >/dev/null 2>&1; then
  warn "docker compose plugin missing — installing"
  case "$OS_ID" in
    ubuntu|debian)
      apt-get update -y >/dev/null
      apt-get install -y docker-compose-plugin >/dev/null
      ;;
    centos|rhel|rocky|almalinux|fedora)
      dnf install -y docker-compose-plugin >/dev/null || yum install -y docker-compose-plugin >/dev/null
      ;;
    *)
      fail "Unsupported OS for compose plugin auto-install. Install 'docker compose' manually."
      ;;
  esac
fi
ok "Compose: $(docker compose version --short)"

# ---- install git if missing ------------------------------------------------
if ! command -v git >/dev/null 2>&1; then
  step "Installing git"
  case "$OS_ID" in
    ubuntu|debian) apt-get install -y git >/dev/null ;;
    centos|rhel|rocky|almalinux|fedora) dnf install -y git >/dev/null || yum install -y git >/dev/null ;;
    *) fail "Install git manually for $OS_ID" ;;
  esac
  ok "git installed"
fi

# ---- clone or update the repo ----------------------------------------------
step "Fetching panel source into $INSTALL_DIR"
if [ -d "$INSTALL_DIR/.git" ]; then
  ok "Existing checkout — pulling latest"
  git -C "$INSTALL_DIR" fetch --depth 1 origin "$REPO_BRANCH"
  git -C "$INSTALL_DIR" reset --hard "origin/$REPO_BRANCH"
else
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone --depth 1 --branch "$REPO_BRANCH" "$REPO_URL" "$INSTALL_DIR"
  ok "Cloned $REPO_URL"
fi

cd "$INSTALL_DIR"

# ---- generate .env if missing ----------------------------------------------
step "Configuring .env"
if [ -f .env ]; then
  ok "Existing .env preserved (delete it manually to regenerate)"
  ADMIN_EMAIL=$(grep -E '^ADMIN_EMAIL=' .env | head -n1 | cut -d= -f2-)
  ADMIN_PASSWORD=$(grep -E '^ADMIN_PASSWORD=' .env | head -n1 | cut -d= -f2-)
  GENERATED_NEW=false
else
  # Generate strong secrets. openssl is universally available where docker is.
  SESSION_SECRET=$(openssl rand -base64 48 | tr -d '\n')
  PANEL_MASTER_KEY=$(openssl rand -base64 32 | tr -d '\n')
  POSTGRES_PASSWORD=$(openssl rand -hex 16)
  ADMIN_PASSWORD=$(openssl rand -base64 18 | tr -d '\n/+=' | head -c 20)
  HOSTNAME_GUESS=$(hostname -f 2>/dev/null || hostname)
  ADMIN_EMAIL="admin@${HOSTNAME_GUESS}"

  cat > .env <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
PANEL_IMAGE=vps-panel:local
PANEL_ORIGIN=http://${HOSTNAME_GUESS}
POSTGRES_USER=panel
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=panel
SESSION_SECRET=${SESSION_SECRET}
PANEL_MASTER_KEY=${PANEL_MASTER_KEY}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF
  chmod 600 .env
  ok "Wrote .env with fresh secrets (chmod 600)"
  GENERATED_NEW=true
fi

# ---- nginx bootstrap conf --------------------------------------------------
step "Setting up nginx bootstrap config"
mkdir -p nginx/conf.d
if [ ! -f nginx/conf.d/panel.conf ]; then
  # Use a catch-all server_name so the panel is reachable by IP before
  # the user sets a real domain via the UI.
  cp deploy/nginx-panel.conf.example nginx/conf.d/panel.conf
  sed -i 's/server_name panel\.example\.com;/server_name _;/g' nginx/conf.d/panel.conf
  ok "Bootstrap nginx config installed (catch-all server_name)"
else
  ok "Existing nginx config kept"
fi

# ---- build the panel image -------------------------------------------------
step "Building panel image (first run takes 2-4 minutes)"
docker compose -f docker-compose.prod.yml --env-file .env build panel >/dev/null
ok "Image built: vps-panel:local"

# ---- start the stack -------------------------------------------------------
step "Starting the stack"
docker compose -f docker-compose.prod.yml --env-file .env up -d
ok "Containers up"

# ---- install panel CLI helper ----------------------------------------------
step "Installing 'panel' CLI helper to /usr/local/bin"
ln -sf "$INSTALL_DIR/scripts/panel-cli.sh" /usr/local/bin/panel
chmod +x "$INSTALL_DIR/scripts/panel-cli.sh"
ok "Now you can run: panel update | panel logs | panel ps"

# ---- wait for healthy ------------------------------------------------------
step "Waiting for panel API to come online"
for i in $(seq 1 60); do
  if docker exec panel_app wget -qO- http://127.0.0.1:4000/api/health >/dev/null 2>&1; then
    ok "Panel API is responding"
    break
  fi
  if [ "$i" = "60" ]; then
    warn "Panel took longer than 60s to start. Check: docker logs panel_app"
  fi
  sleep 1
done

# ---- final summary ---------------------------------------------------------
PUBLIC_IP=$(curl -fsS --max-time 3 https://api.ipify.org 2>/dev/null || echo "<your VPS IP>")

echo
echo -e "${C_GREEN}${C_BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C_RESET}"
echo -e "${C_GREEN}${C_BOLD}  VPS Panel is up.${C_RESET}"
echo -e "${C_GREEN}${C_BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C_RESET}"
echo
echo -e "  ${C_BOLD}URL:${C_RESET}      http://${PUBLIC_IP}"
echo -e "  ${C_BOLD}Email:${C_RESET}    ${ADMIN_EMAIL}"
if [ "$GENERATED_NEW" = "true" ]; then
  echo -e "  ${C_BOLD}Password:${C_RESET} ${ADMIN_PASSWORD}   ${C_YELLOW}← save this — won't be shown again${C_RESET}"
else
  echo -e "  ${C_BOLD}Password:${C_RESET} (kept from existing .env)"
fi
echo
echo -e "  Next steps:"
echo -e "    1. Log in → Settings → ${C_BOLD}enable 2FA${C_RESET}"
echo -e "    2. Settings → Panel domain → set ${C_BOLD}panel.yourdomain.com${C_RESET} and issue SSL"
echo -e "    3. Apps / Projects → start deploying"
echo
echo -e "  Helpful commands:"
echo -e "    panel logs       — tail panel logs"
echo -e "    panel ps         — list containers"
echo -e "    panel update     — pull latest code and restart"
echo
