import { simpleGit } from "simple-git";
import tarFs from "tar-fs";
import { rm, mkdtemp, readdir, writeFile, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { docker } from "../docker.js";

export type BuildMode = "dockerfile" | "static";

export interface BuildInput {
  slug: string;
  repoUrl: string;
  branch: string;
  buildMode: BuildMode;
  dockerfilePath?: string; // dockerfile mode, defaults to "Dockerfile"
  publishDir?: string; // static mode, defaults to "."
  gitToken?: string;
  onLog: (line: string) => void;
}

const STATIC_DOCKERFILE = (publishDir: string) => `# Auto-generated by VPS Panel for static site
FROM nginx:alpine
COPY ${publishDir} /usr/share/nginx/html
EXPOSE 80
`;

const STATIC_DOCKERIGNORE = `# Auto-generated by VPS Panel
.git
node_modules
.env
.env.*
Dockerfile.panel
.dockerignore.panel
`;


export interface BuildResult {
  imageTag: string;
  gitSha: string;
}

function authedRepoUrl(repoUrl: string, token?: string): string {
  if (!token) return repoUrl;
  try {
    const u = new URL(repoUrl);
    // GitHub: x-access-token / GitLab: oauth2 / generic: just use as username
    u.username = "x-access-token";
    u.password = token;
    return u.toString();
  } catch {
    return repoUrl;
  }
}

export async function buildFromGit(input: BuildInput): Promise<BuildResult> {
  const {
    slug,
    repoUrl,
    branch,
    buildMode,
    dockerfilePath = "Dockerfile",
    publishDir = ".",
    gitToken,
    onLog,
  } = input;

  const workDir = await mkdtemp(path.join(tmpdir(), `panel-build-${slug}-`));
  onLog(`workdir: ${workDir}`);

  try {
    // 1. Clone
    onLog(`cloning ${repoUrl} (branch=${branch}) ...`);
    const git = simpleGit();
    await git.clone(authedRepoUrl(repoUrl, gitToken), workDir, [
      "--depth",
      "1",
      "--branch",
      branch,
      "--single-branch",
    ]);

    // 2. Resolve git sha
    const repoGit = simpleGit(workDir);
    const gitSha = (await repoGit.revparse(["HEAD"])).trim().slice(0, 12);
    onLog(`HEAD: ${gitSha}`);

    // 3. Resolve dockerfile path based on build mode
    let effectiveDockerfile = dockerfilePath;

    if (buildMode === "static") {
      // Validate publishDir exists and contains index.html (warn if not)
      const fullPublishPath = path.join(workDir, publishDir);
      try {
        const s = await stat(fullPublishPath);
        if (!s.isDirectory()) {
          throw new Error(`publishDir "${publishDir}" is not a directory`);
        }
      } catch {
        throw new Error(`publishDir "${publishDir}" not found in repo`);
      }
      const publishFiles = await readdir(fullPublishPath);
      if (!publishFiles.includes("index.html")) {
        onLog(`WARN: no index.html in "${publishDir}" — nginx will return 404 at /`);
      }

      // Write auto-generated Dockerfile + .dockerignore
      effectiveDockerfile = "Dockerfile.panel";
      await writeFile(
        path.join(workDir, effectiveDockerfile),
        STATIC_DOCKERFILE(publishDir),
      );
      // Only write .dockerignore if repo doesn't already have one
      const files = await readdir(workDir);
      if (!files.includes(".dockerignore")) {
        await writeFile(path.join(workDir, ".dockerignore"), STATIC_DOCKERIGNORE);
      }
      onLog(`static mode: generated ${effectiveDockerfile} (publish dir = ${publishDir})`);
    } else {
      // dockerfile mode: must exist
      const files = await readdir(workDir);
      if (!files.includes(effectiveDockerfile)) {
        throw new Error(`${effectiveDockerfile} not found at repo root`);
      }
    }

    // 4. Build
    const imageTag = `panel/${slug}:${gitSha}`;
    onLog(`building image ${imageTag} ...`);

    const tarStream = tarFs.pack(workDir);
    const buildStream = await docker.buildImage(tarStream, {
      t: imageTag,
      dockerfile: effectiveDockerfile,
      rm: true,
      forcerm: true,
    });

    await new Promise<void>((resolve, reject) => {
      docker.modem.followProgress(
        buildStream,
        (err, _output) => {
          if (err) reject(err);
          else resolve();
        },
        (event: { stream?: string; error?: string; errorDetail?: { message?: string } }) => {
          if (event.error) {
            onLog(`ERROR: ${event.errorDetail?.message ?? event.error}`);
          } else if (event.stream) {
            const trimmed = event.stream.replace(/\n$/, "");
            if (trimmed) onLog(trimmed);
          }
        },
      );
    });

    // 5. Also tag as :latest for convenience
    const latestTag = `panel/${slug}:latest`;
    await docker.getImage(imageTag).tag({ repo: `panel/${slug}`, tag: "latest" });
    onLog(`tagged also as ${latestTag}`);

    onLog(`build complete: ${imageTag}`);
    return { imageTag, gitSha };
  } finally {
    // Cleanup workdir
    await rm(workDir, { recursive: true, force: true }).catch(() => {});
  }
}
